-- Exécuter dans Supabase SQL Editor AVANT de déployer cette version.
-- Migration additive : conserve tous les profils existants.
BEGIN;
ALTER TABLE public.dj_profiles
  ADD COLUMN IF NOT EXISTS cover_avatar INTEGER,
  ADD COLUMN IF NOT EXISTS service_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS mixcloud TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS youtube TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS spotify TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS video_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiktok TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS website TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS travel_areas TEXT NOT NULL DEFAULT '';
COMMIT;
