// Run with PLAYWRIGHT_MODULE pointing to an installed Playwright package, or install it separately.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const path=require('node:path');
const root=path.resolve(__dirname,'../public');
const express=require('express');
const assert=require('node:assert/strict');
(async()=>{
 const app=express();app.use(express.static(root));
 const server=app.listen(3107,'127.0.0.1');
 let browser;
 try{
 browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{channel:'chrome'}),headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844}});
 let photoFailure=true, gallery=[], saved=null;
 const publicProfile={id:'public-test',stage_name:'DJ Public',city:'Lyon, France',tagline:'Afro house et amapiano',bio:'Présentation publique.',genres:'Shatta, Afrobeats, Amapiano, Hip-hop, Zouk, House',service_types:['Club','Festival'],soundcloud:'https://soundcloud.com/public',mixcloud:'https://www.mixcloud.com/public/mix/',youtube:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',spotify:'https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg',instagram:'https://instagram.com/public',booking_email:'booking@example.com',travel_areas:'France et Europe',cover_avatar:3,photo_url:'/images/auth-hero-bg.jpg',gallery:['/images/logo.png']};
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{
  const u=new URL(route.request().url());
  if(u.hostname!=='127.0.0.1')return route.abort();
  if(u.pathname==='/api/dj/profile/photo')return route.fulfill({status:photoFailure?500:200,contentType:'application/json',body:JSON.stringify(photoFailure?{error:'Échec photo simulé'}:{url:'/images/logo.png'})});
  if(u.pathname==='/api/dj/profile/gallery'){
   if(route.request().method()==='DELETE')gallery=gallery.filter(x=>x!==route.request().postDataJSON().url);
   else gallery.push('/images/logo.png?gallery='+gallery.length);
   return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({gallery,url:gallery.at(-1)})});
  }
  if(u.pathname==='/api/dj/profile' && route.request().method()==='POST') {saved=route.request().postDataJSON();return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...saved,id:'test',photo_url:'/images/logo.png',gallery})});}
  if(u.pathname==='/api/dj/profile/public-test')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(publicProfile)});
  if(u.pathname.startsWith('/api/'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(u.pathname==='/api/config/public'?{}:[])});
  return route.continue();
 });
 await page.goto('http://127.0.0.1:3107/index.html');
 await page.waitForTimeout(500);
 await page.evaluate(()=>{
  _sbSession={access_token:'test',user:{id:'test'}};currentUser={uid:'test',displayName:'DJ Test'};_djProfileCache={};
  openDjRegister();
 });
 await page.locator('#djr-editor').waitFor({state:'visible'});
 assert.equal(await page.locator('#dj-edit-tagline').getAttribute('maxlength'),'150');
 await page.locator('#btn-save-dj-profile').click();
 assert.match(await page.locator('#djr-feedback').innerText(),/Complète/);
 const genreInputs=page.locator('#djr-genres input');for(let i=0;i<6;i++)await genreInputs.nth(i).check();
 assert.equal(await genreInputs.nth(6).isDisabled(),true);
 await genreInputs.nth(0).uncheck();assert.equal(await genreInputs.nth(6).isDisabled(),false);
 await page.locator('#djr-genre-search').fill('zouk');assert.equal(await page.locator('#djr-genres label:visible').count(),5);
 await page.locator('#djr-genre-search').fill('');
 await page.locator('.djr-cover-picker').evaluate(details=>details.open=true);
 assert.equal(await page.locator('#djr-cover-options input').count(),21);
 await page.locator('#djr-cover-options img').evaluateAll(images=>images.forEach(img=>img.loading='eager'));
 await page.locator('#djr-cover-options img').first().waitFor({state:'visible'});
 assert.equal(await page.locator('#dj-edit-city').count(),0);
 assert.equal(await page.locator('#djr-cities').count(),0);
 assert.equal(await page.evaluate(()=>document.querySelector('#djr-editor').scrollWidth<=document.querySelector('#djr-editor').clientWidth),true);
 await page.evaluate(()=>{_djProfileCache={photo_url:'/images/logo.png'};initDjProfileEditor({stage_name:'DJ Nova',tagline:'House music',bio:'Biographie',genres:'House',service_types:['Club'],soundcloud:'https://soundcloud.com/nova',booking_email:'booking@example.com'});});
 const result=await page.evaluate(()=>collectDjProfile());assert.equal(result.stage_name,'DJ Nova');assert.equal(result.genres,'House');
 await page.evaluate(()=>{_djProfileCache={};});
 await page.locator('#dj-photo-input').setInputFiles(path.join(root,'images/logo.png'));
 await page.waitForFunction(()=>!djMediaBusy);assert.match(await page.locator('#djr-feedback').innerText(),/Échec/);
 assert.equal(await page.evaluate(()=>!!_djProfileCache.photo_url),false);
 photoFailure=false;
 await page.locator('#dj-photo-input').setInputFiles(path.join(root,'images/logo.png'));
 await page.waitForFunction(()=>!djMediaBusy);assert.equal(await page.evaluate(()=>_djProfileCache.photo_url),'/images/logo.png');
 await page.locator('#djr-gallery-input').setInputFiles(path.join(root,'images/logo.png'));
 await page.waitForFunction(()=>!djMediaBusy);assert.equal(await page.locator('#djr-gallery img').count(),1);
 await page.locator('#djr-gallery button').click();await page.waitForFunction(()=>!djMediaBusy);assert.equal(await page.locator('#djr-gallery img').count(),0);
 await page.evaluate(()=>{djGallery=Array.from({length:6},(_,i)=>'/images/logo.png?'+i);renderDjGallery();});
 await page.locator('#djr-gallery-input').setInputFiles(path.join(root,'images/logo.png'));
 assert.match(await page.locator('#djr-feedback').innerText(),/6 photos/);assert.equal(gallery.length,0);
 await page.evaluate(()=>{djGallery=[];renderDjGallery();});
 await page.locator('#djr-cover-options input[value="3"]').check();
 await page.locator('.djr-cover-picker').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-avatar-picker-mobile.png'),fullPage:true});
 await page.locator('#btn-save-dj-profile').click();await page.waitForFunction(()=>document.getElementById('btn-save-dj-profile').textContent==='Enregistrer mon profil');
 assert.equal(saved.cover_avatar,3);assert.equal(saved.service_types[0],'Club');assert.equal(saved.soundcloud,'https://soundcloud.com/nova');
 await page.evaluate(()=>{openDjRegister();document.querySelector('#pg-dj-register .scroll').scrollTop=0;});
 await page.locator('.djr-cover-picker').evaluate(el=>el.open=false);
 await page.waitForTimeout(500);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-profile-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1280,height:900});await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-profile-desktop.png'),fullPage:true});
 await page.evaluate(()=>{_djProfileCache={..._djProfileCache,bio:'Présentation test',experience:'Club test',service_types:['Club'],genres:'House',gallery:['/images/logo.png'],tiktok:'https://tiktok.com/@test',website:'https://example.com',video_url:'https://youtube.com/watch?v=test',phone:'+33 6 12 34 56 78',travel_areas:'France'};showPage('presskit');});
 assert.match(await page.locator('#pk-profile-details').innerText(),/Présentation test/);
 assert.match(await page.locator('#pk-profile-details').innerText(),/Club test/);
 assert.equal(await page.locator('#pk-services').count(),0);
 assert.equal(await page.locator('#pk-about .pk-profile-chips span').allTextContents().then(values=>values.join(',')),'Club');
 assert.equal(await page.locator('#pk-profile-details h2').filter({hasText:'Prestations'}).count(),0);
 assert.equal(await page.locator('#pk-profile-details a[href="https://tiktok.com/@test"]').count(),1);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery img').count(),1);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery a').count(),0);
 assert.match(await page.locator('#pk-hero-art').evaluate(el=>el.style.backgroundImage),/logo\.png/);
 assert.match(await page.locator('#pk-photo').getAttribute('src'),/avatar-03-pullup\.png/);
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://127.0.0.1:3107/index.html?dj=public-test');
 await page.locator('#pg-presskit.active').waitFor();
 assert.equal(await page.locator('#pk-name').innerText(),'DJ PUBLIC');
 assert.equal(await page.locator('.pk2-header-label').innerText(),'ARTIST PRESS KIT');
 assert.equal(await page.locator('.pk2-header-label').evaluate(el=>el.tagName),'SPAN');
 assert.equal(await page.locator('#pk-location').count(),0);
 assert.doesNotMatch(await page.locator('.pk2-hero').innerText(),/Lyon|PROFIL DJ/i);
 assert.equal(await page.locator('#pk-edit-btn').isVisible(),false);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery img').count(),1);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery a').count(),0);
 assert.equal(await page.locator('#pk-about').count(),1);
 assert.equal(await page.locator('#pk-music').count(),1);
 assert.equal(await page.locator('#pk-booking').isVisible(),true);
 assert.equal(await page.evaluate(()=>Boolean(document.querySelector('.pk2-live').compareDocumentPosition(document.querySelector('#pk-profile-details'))&Node.DOCUMENT_POSITION_FOLLOWING)),true);
 assert.equal(await page.locator('#pk-socials').count(),0);
 assert.equal(await page.locator('#pk-music a').count(),0);
 assert.equal(await page.locator('#pk-music .pk-profile-player').count(),4);
 assert.match(await page.locator('#pk-music [data-platform="soundcloud"] iframe').getAttribute('src'),/^https:\/\/w\.soundcloud\.com\/player\//);
 assert.match(await page.locator('#pk-music [data-platform="mixcloud"] iframe').getAttribute('src'),/^https:\/\/www\.mixcloud\.com\/widget\/iframe\//);
 assert.match(await page.locator('#pk-music [data-platform="youtube"] iframe').getAttribute('src'),/^https:\/\/www\.youtube-nocookie\.com\/embed\//);
 assert.match(await page.locator('#pk-music [data-platform="spotify"] iframe').getAttribute('src'),/^https:\/\/open\.spotify\.com\/embed\//);
 assert.equal(await page.evaluate(()=>document.querySelector('#pk-booking').getBoundingClientRect().top>document.querySelector('#pk-profile-details').getBoundingClientRect().top),true);
 assert.match(await page.locator('#pk-hero-art').evaluate(el=>el.style.backgroundImage),/auth-hero-bg\.jpg/);
 assert.match(await page.locator('#pk-photo').getAttribute('src'),/avatar-03-pullup\.png/);
 assert.equal(await page.locator('#pk-genre-chips span').count(),6);
 assert.equal(await page.locator('#pk-genre-chips span').evaluateAll(chips=>new Set(chips.map(chip=>chip.offsetTop)).size),1);
 assert.equal(await page.evaluate(()=>{const hero=document.querySelector('.pk2-hero').getBoundingClientRect(),photo=document.querySelector('.pk3-avatar-stage').getBoundingClientRect();return Math.abs(hero.width-photo.width)<=2&&Math.abs(hero.height-photo.height)<=2;}),true);
 assert.equal(await page.evaluate(()=>djProfileUrl()),'http://127.0.0.1:3107/app?dj=public-test');
 assert.equal(await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 await page.waitForTimeout(500);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-mobile.png'),fullPage:true});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=620);
 await page.waitForTimeout(200);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-mobile-content.png'),fullPage:true});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=el.scrollHeight);
 await page.waitForTimeout(200);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-mobile-bottom.png'),fullPage:true});
 await page.setViewportSize({width:1280,height:900});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=0);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-desktop-top.png'),fullPage:true});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=760);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-desktop.png'),fullPage:true});
 const relevant=errors.filter(e=>!e.includes('supabase')&&!e.includes('QRCode'));
 console.log('Browser errors:',errors);
 assert.deepEqual(relevant,[]);
 console.log('PASS: mobile/desktop, validation, six styles, search, 20 covers, form round-trip, press kit header; screenshots in /private/tmp.');
 }finally{await browser?.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
