// Run with PLAYWRIGHT_MODULE pointing to an installed Playwright package, or install it separately.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const path=require('node:path');
const root=path.resolve(__dirname,'../public');
const express=require('express');
const assert=require('node:assert/strict');
(async()=>{
 const app=express();app.use(express.static(root));
 const server=app.listen(3107,'127.0.0.1');
 let browser;
 try{
 browser=await chromium.launch({...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{channel:'chrome'}),headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844}});
 await page.addInitScript(()=>{function TestQRCode(element,options){const canvas=document.createElement('canvas');canvas.width=options.width;canvas.height=options.height;element.append(canvas);}TestQRCode.CorrectLevel={H:2};window.QRCode=TestQRCode;});
 let photoFailure=true, gallery=[], saved=null;
 const publicProfile={id:'public-test',slug:'dj-public',stage_name:'DJ Public',city:'Lyon, France',tagline:'Afro house et amapiano',bio:'Présentation publique.',genres:'Shatta, Afrobeats, Amapiano, Hip-hop, Zouk, House',service_types:['Club','Festival'],soundcloud:'https://soundcloud.com/public',mixcloud:'[mixcloud https://www.mixcloud.com/emilio-lameynardie/afro-vs-shatta-dj-paul-keranne-hustle-and-flow/ width=100% height=120 hide_cover=1 autoplay=1]',youtube:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',spotify:'https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg',instagram:'https://instagram.com/public',booking_email:'booking@example.com',travel_areas:'France et Europe',cover_avatar:3,photo_url:'/images/auth-hero-bg.jpg',gallery:['/images/logo.png'],presskit_pdf_url:'https://example.com/dj-public-presskit.pdf',upcoming_events:[{flyer_url:'/images/logo.png',date:'2026-10-18',name:'Hustle & Flow',place:'Le Balajo',address:'9 Rue de Lappe, 75011 Paris',link_url:'https://example.com/event'},{flyer_url:'/images/auth-hero-bg.jpg',date:'2026-10-26',name:'Afro Night',place:'Le Sucre',address:'50 Quai Rambaud, 69002 Lyon',link_url:'https://example.com/afro'}]};
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{
  const u=new URL(route.request().url());
  if(u.hostname!=='127.0.0.1')return route.abort();
  if(u.pathname==='/api/dj/profile/photo')return route.fulfill({status:photoFailure?500:200,contentType:'application/json',body:JSON.stringify(photoFailure?{error:'Échec photo simulé'}:{url:'/images/logo.png'})});
  if(u.pathname==='/api/dj/profile/gallery'){
   if(route.request().method()==='DELETE')gallery=gallery.filter(x=>x!==route.request().postDataJSON().url);
   else gallery.push('/images/logo.png?gallery='+gallery.length);
   return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({gallery,url:gallery.at(-1)})});
  }
  if(u.pathname==='/api/dj/profile/event-flyer')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({url:'https://storage.example/profile-photos/dj/test/event-flyer-1.jpg'})});
  if(u.pathname==='/api/dj/profile/presskit-pdf')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({url:route.request().method()==='DELETE'?'':'https://storage.example/profile-photos/dj/test/presskit.pdf?v=1'})});
  if(u.pathname.startsWith('/api/dj/slug-availability/')){const slug=decodeURIComponent(u.pathname.split('/').at(-1));return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({slug,available:slug!=='dj-deja-pris'})});}
  if(u.pathname==='/api/dj/profile' && route.request().method()==='POST') {saved=route.request().postDataJSON();return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...saved,id:'test',photo_url:'/images/logo.png',gallery})});}
  if(u.pathname==='/api/dj/profile/public-test')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(publicProfile)});
  if(u.pathname.startsWith('/api/'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(u.pathname==='/api/config/public'?{}:[])});
  return route.continue();
 });
 await page.goto('http://127.0.0.1:3107/index.html');
 await page.waitForTimeout(500);
 await page.evaluate(()=>{
  _sbSession={access_token:'test',user:{id:'test'}};currentUser={uid:'test',displayName:'DJ Test'};_djProfileCache={};
  openDjRegister();
 });
 await page.locator('#djr-editor').waitFor({state:'visible'});
 assert.equal(await page.locator('#dj-edit-slug').evaluate(el=>getComputedStyle(el).fontSize),'16px');
 assert.equal(await page.locator('#dj-edit-tagline').getAttribute('maxlength'),'150');
 assert.match(await page.locator('#djr-pdf-status').innerText(),/Aucun PDF/);
 assert.match(await page.locator('.djr-photo-row p').innerText(),/recadrage et zoom/);
 assert.equal(await page.locator('[data-error="mixes"]').evaluate(el=>el.previousElementSibling.textContent),'Choisis SoundCloud, Mixcloud ou Spotify, puis colle le lien de ta playlist ou de ton mix. YouTube reste disponible pour une vidéo ou une playlist.');
 assert.equal(await page.locator('#dj-edit-spotify').getAttribute('placeholder'),'Lien de ta playlist Spotify');
 await page.locator('#btn-save-dj-profile').click();
 assert.match(await page.locator('#djr-feedback').innerText(),/Complète/);
 const genreInputs=page.locator('#djr-genres input');for(let i=0;i<6;i++)await genreInputs.nth(i).check();
 assert.equal(await genreInputs.nth(6).isDisabled(),true);
 await genreInputs.nth(0).uncheck();assert.equal(await genreInputs.nth(6).isDisabled(),false);
 await page.locator('#djr-genre-search').fill('zouk');assert.equal(await page.locator('#djr-genres label:visible').count(),5);
 await page.locator('#djr-genre-search').fill('');
 await page.locator('.djr-cover-picker').evaluate(details=>details.open=true);
 assert.equal(await page.locator('#djr-cover-options input').count(),21);
 assert.equal(await page.locator('.djr-event-card').count(),1);
 await page.fill('#dj-event-0-name','Brouillon');
 for(let i=0;i<3;i++)await page.locator('.djr-event-add').click();
 assert.equal(await page.locator('.djr-event-card').count(),4);
 assert.equal(await page.locator('.djr-event-add').count(),0);
 assert.equal(await page.inputValue('#dj-event-0-name'),'Brouillon');
 await page.locator('.djr-event-remove').last().click();
 assert.equal(await page.locator('.djr-event-card').count(),3);
 await page.locator('#djr-cover-options img').evaluateAll(images=>images.forEach(img=>img.loading='eager'));
 await page.locator('#djr-cover-options img').first().waitFor({state:'visible'});
 assert.equal(await page.locator('#dj-edit-city').count(),0);
 assert.equal(await page.locator('#djr-cities').count(),0);
 assert.equal(await page.evaluate(()=>document.querySelector('#djr-editor').scrollWidth<=document.querySelector('#djr-editor').clientWidth),true);
 await page.evaluate(()=>{_djProfileCache={photo_url:'/images/logo.png'};initDjProfileEditor({stage_name:'DJ Nova',tagline:'House music',bio:'Biographie',genres:'House',service_types:['Club'],soundcloud:'https://soundcloud.com/nova',booking_email:'booking@example.com'});});
 assert.equal(await page.inputValue('#dj-edit-slug'),'dj-nova');
 assert.equal(await page.locator('#djr-public-url-preview').innerText(),'pull-up.live/dj-nova');
 await page.waitForFunction(()=>document.getElementById('djr-slug-status').dataset.state==='available');
 await page.fill('#dj-edit-slug','DJ Étoile Paris');assert.equal(await page.inputValue('#dj-edit-slug'),'dj-etoile-paris');
 await page.fill('#dj-edit-slug','DJ déjà pris');await page.waitForFunction(()=>document.getElementById('djr-slug-status').dataset.state==='taken');assert.match(await page.locator('#djr-slug-status').innerText(),/déjà prise/);
 await page.fill('#dj-edit-slug','DJ Étoile Paris');await page.waitForFunction(()=>document.getElementById('djr-slug-status').dataset.state==='available');
 const result=await page.evaluate(()=>collectDjProfile());assert.equal(result.stage_name,'DJ Nova');assert.equal(result.genres,'House');assert.equal(result.slug,'dj-etoile-paris');
 await page.locator('#djr-pdf-input').setInputFiles({name:'presskit.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\\n')});
 await page.waitForFunction(()=>!djMediaBusy&&_djProfileCache.presskit_pdf_url?.includes('presskit.pdf'));
 assert.equal(await page.locator('#djr-pdf-link').isVisible(),true);
 const editorUrl=page.url();
 await page.locator('#djr-pdf-link').click();
 assert.equal(await page.locator('#djr-pdf-preview-modal').isVisible(),true);
 assert.match(await page.locator('#djr-pdf-preview-frame').getAttribute('src'),/presskit-pdf\/download\?preview=1$/);
 await page.locator('.djr-pdf-preview-close').click();
 assert.equal(await page.locator('#djr-pdf-preview-modal').isHidden(),true);
 assert.equal(page.url(),editorUrl);
 await page.locator('#djr-pdf-remove').click();await page.waitForFunction(()=>!djMediaBusy&&!_djProfileCache.presskit_pdf_url);
 assert.match(await page.locator('#djr-pdf-status').innerText(),/Aucun PDF/);
 await page.evaluate(()=>{_djProfileCache={};});
 await page.locator('#dj-photo-input').setInputFiles(path.join(root,'images/logo.png'));
 await page.waitForFunction(()=>djPhotoCropState?.ready===true);
 assert.ok((await page.locator('#djr-crop-stage').boundingBox()).width>300);
 assert.ok((await page.locator('#dj-edit-avatar').boundingBox()).width>100);
 await page.locator('#djr-crop-range').fill('1.5');
 const cropBox=await page.locator('#djr-crop-stage').boundingBox();await page.mouse.move(cropBox.x+cropBox.width/2,cropBox.y+cropBox.height/2);await page.mouse.down();await page.mouse.move(cropBox.x+cropBox.width/2+24,cropBox.y+cropBox.height/2+18);await page.mouse.up();assert.notEqual(await page.evaluate(()=>djPhotoCropState.x),0);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-photo-crop-mobile.png'),fullPage:true});
 await page.locator('.djr-crop-apply').click();await page.waitForFunction(()=>document.getElementById('djr-crop-modal').hidden&&!djMediaBusy);assert.match(await page.locator('#djr-feedback').innerText(),/Échec/);
 assert.equal(await page.evaluate(()=>!!_djProfileCache.photo_url),false);
 photoFailure=false;
 await page.locator('#dj-photo-input').setInputFiles(path.join(root,'images/logo.png'));
 await page.waitForFunction(()=>djPhotoCropState?.ready===true);
 await page.locator('.djr-crop-apply').click();await page.waitForFunction(()=>document.getElementById('djr-crop-modal').hidden&&!djMediaBusy);assert.equal(await page.evaluate(()=>_djProfileCache.photo_url),'/images/logo.png');
 await page.locator('#djr-gallery-input').setInputFiles(path.join(root,'images/logo.png'));
 await page.waitForFunction(()=>!djMediaBusy);assert.equal(await page.locator('#djr-gallery img').count(),1);
 await page.locator('#djr-gallery button').click();await page.waitForFunction(()=>!djMediaBusy);assert.equal(await page.locator('#djr-gallery img').count(),0);
 await page.evaluate(()=>{djGallery=Array.from({length:6},(_,i)=>'/images/logo.png?'+i);renderDjGallery();});
 await page.locator('#djr-gallery-input').setInputFiles(path.join(root,'images/logo.png'));
 assert.match(await page.locator('#djr-feedback').innerText(),/6 photos/);assert.equal(gallery.length,0);
 await page.evaluate(()=>{djGallery=[];renderDjGallery();});
 await page.locator('#djr-cover-options input[value="3"]').check();
 await page.locator('#dj-event-0-flyer-input').setInputFiles(path.join(root,'images/logo.png'));
 await page.waitForFunction(()=>!djMediaBusy&&document.getElementById('dj-event-0-flyer-url').value.includes('event-flyer'));
 assert.match(await page.locator('#djr-feedback').innerText(),/Flyer chargé/);
 await page.locator('#dj-event-0-date').fill('2026-10-18');
 await page.locator('#dj-event-0-name').fill('Hustle & Flow');
 await page.locator('#dj-event-0-place').fill('Le Balajo');
 await page.locator('#dj-event-0-address').fill('9 Rue de Lappe, 75011 Paris');
 await page.locator('#dj-event-0-link-url').fill('https://example.com/event');
 await page.locator('.djr-cover-picker').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-avatar-picker-mobile.png'),fullPage:true});
 await page.locator('#btn-save-dj-profile').click();await page.waitForFunction(()=>document.getElementById('btn-save-dj-profile').textContent==='Enregistrer mon profil');
 assert.equal(saved.cover_avatar,3);assert.equal(saved.service_types[0],'Club');assert.equal(saved.soundcloud,'https://soundcloud.com/nova');assert.equal(saved.upcoming_events[0].name,'Hustle & Flow');assert.equal(saved.upcoming_events[0].address,'9 Rue de Lappe, 75011 Paris');
 await page.evaluate(()=>{openDjRegister();document.querySelector('#pg-dj-register .scroll').scrollTop=0;});
 await page.locator('.djr-cover-picker').evaluate(el=>el.open=false);
 await page.waitForTimeout(500);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-profile-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1280,height:900});await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-profile-desktop.png'),fullPage:true});
 await page.evaluate(()=>{_djProfileCache={..._djProfileCache,bio:'Présentation test',experience:'Club test',service_types:['Club'],genres:'House',gallery:['/images/logo.png'],tiktok:'https://tiktok.com/@test',website:'https://example.com',video_url:'https://youtube.com/watch?v=test',phone:'+33 6 12 34 56 78',travel_areas:'France'};showPage('presskit');});
 assert.match(await page.locator('#pk-profile-details').innerText(),/Présentation test/);
 assert.match(await page.locator('#pk-profile-details').innerText(),/Club test/);
 assert.equal(await page.locator('#pk-services').count(),0);
 assert.equal(await page.locator('#pk-about .pk-profile-chips span').allTextContents().then(values=>values.join(',')),'Club');
 assert.equal(await page.locator('#pk-profile-details h2').filter({hasText:'Prestations'}).count(),0);
 assert.equal(await page.locator('#pk-profile-details a[href="https://tiktok.com/@test"]').count(),1);
 assert.equal(await page.locator('#pk-links h2').innerText(),'RÉSEAUX');
 assert.ok(await page.locator('#pk-links .pk-social-icon').count()>=3);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery img').count(),1);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery a').count(),0);
 assert.match(await page.locator('#pk-hero-art').evaluate(el=>el.style.backgroundImage),/logo\.png/);
 assert.match(await page.locator('#pk-photo').getAttribute('src'),/avatar-03-pullup\.png/);
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://127.0.0.1:3107/index.html?dj=public-test');
 await page.locator('#pg-presskit.active').waitFor();
 assert.equal(await page.locator('#pk-name').innerText(),'DJ PUBLIC');
 assert.equal(await page.locator('.pk2-header-label').innerText(),'ARTIST PRESS KIT');
 assert.equal(await page.locator('.pk2-header-label').evaluate(el=>el.tagName),'SPAN');
 assert.equal(await page.locator('#pk-location').count(),0);
 assert.doesNotMatch(await page.locator('.pk2-hero').innerText(),/Lyon|PROFIL DJ/i);
 assert.equal(await page.locator('#pk-edit-btn').isVisible(),false);
 assert.equal(await page.locator('#pk-public-url').innerText(),'pull-up.live/dj-public');
 assert.equal(await page.locator('#pk-public-url').getAttribute('href'),'http://127.0.0.1:3107/dj-public');
 assert.equal(await page.locator('#pk-public-qr canvas').count(),1);
 assert.equal(await page.locator('#pk-public-qr-logo').getAttribute('src'),'/images/logo.png');
 assert.deepEqual(await page.locator('#pk-public-share button').allTextContents(),['Copier le lien','Partager','Télécharger le QR']);
 assert.equal(await page.locator('#pk-public-share h2').innerText(),'PARTAGER CE PROFIL');
 assert.match(await page.locator('.pk3-create-cta').innerText(),/Crée ton Press Kit/);
 assert.doesNotMatch(await page.locator('.pk3-footer').innerText(),/Partager ce profil/);
 assert.ok((await page.locator('#pk-public-share button').first().boundingBox()).height>=44);
 assert.ok((await page.locator('.pk3-create-cta').boundingBox()).height>=44);
 assert.equal(await page.locator('#pg-presskit').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery img').count(),1);
 assert.equal(await page.locator('#pk-profile-details .pk-profile-gallery a').count(),0);
 assert.equal(await page.locator('#pk-about').count(),1);
 assert.equal(await page.locator('#pk-music').count(),1);
 assert.equal(await page.locator('#pk-upcoming-events .pk-profile-event').count(),2);
 assert.match(await page.locator('#pk-upcoming-events').innerText(),/HUSTLE & FLOW/);
 assert.equal(await page.locator('#pk-upcoming-events a[href="https://example.com/event"]').count(),1);
 await page.evaluate(profile=>{_djProfileCache={...profile,upcoming_events:[]};showPage('presskit');},publicProfile);
 assert.equal(await page.locator('#pk-upcoming-events').count(),0);
 await page.evaluate(profile=>{_djProfileCache={...profile,upcoming_events:[profile.upcoming_events[0]]};showPage('presskit');},publicProfile);
 assert.equal(await page.locator('#pk-upcoming-events .pk-profile-event').count(),1);
 assert.match(await page.locator('#pk-upcoming-events').innerText(),/9 Rue de Lappe/);
 await page.evaluate(profile=>{_djProfileCache={...profile,upcoming_events:[{name:'Soirée partielle'},{place:'Paris'},{date:'2026-10-18'},{address:'9 Rue de Lappe'}]};showPage('presskit');},publicProfile);
 assert.equal(await page.locator('#pk-upcoming-events .pk-profile-event').count(),4);
 assert.equal(await page.locator('#pk-upcoming-events a').count(),0);
 await page.evaluate(profile=>{_djProfileCache=profile;showPage('presskit');},publicProfile);
 assert.equal(await page.locator('#pk-booking').isVisible(),true);
 assert.equal(await page.locator('#pk-booking-contact').count(),0);
 assert.equal(await page.locator('.pk2-print').count(),0);
 assert.equal(await page.locator('#pk-presskit-pdf').isVisible(),true);
 assert.equal(await page.locator('#pk-presskit-pdf').getAttribute('href'),'https://example.com/dj-public-presskit.pdf');
 assert.equal(await page.evaluate(()=>Boolean(document.querySelector('.pk2-live').compareDocumentPosition(document.querySelector('#pk-profile-details'))&Node.DOCUMENT_POSITION_FOLLOWING)),true);
 assert.equal(await page.locator('#pk-socials').count(),0);
 assert.equal(await page.locator('#pk-music a').count(),0);
 assert.equal(await page.locator('#pk-music .pk-profile-player').count(),4);
 // RGPD : aucun lecteur tiers ne doit charger avant un clic explicite —
 // seuls des placeholders avec bouton "Afficher le lecteur" sont présents.
 assert.equal(await page.locator('#pk-music iframe').count(),0);
 assert.equal(await page.locator('#pk-music .pk-profile-player-gate').count(),4);
 assert.match(await page.locator('#pk-music [data-platform="soundcloud"] .pk-profile-player-gate p').innerText(),/fourni par SoundCloud/);
 await page.locator('#pk-music [data-platform="soundcloud"] button').click();
 assert.match(await page.locator('#pk-music [data-platform="soundcloud"] iframe').getAttribute('src'),/^https:\/\/w\.soundcloud\.com\/player\//);
 await page.locator('#pk-music [data-platform="mixcloud"] button').click();
 assert.match(await page.locator('#pk-music [data-platform="mixcloud"] iframe').getAttribute('src'),/^https:\/\/player-widget\.mixcloud\.com\//);
 assert.match(await page.locator('#pk-music [data-platform="mixcloud"] iframe').getAttribute('src'),/feed=%2Femilio-lameynardie%2Fafro-vs-shatta/);
 await page.locator('#pk-music [data-platform="youtube"] button').click();
 assert.match(await page.locator('#pk-music [data-platform="youtube"] iframe').getAttribute('src'),/^https:\/\/www\.youtube-nocookie\.com\/embed\//);
 await page.locator('#pk-music [data-platform="spotify"] button').click();
 assert.match(await page.locator('#pk-music [data-platform="spotify"] iframe').getAttribute('src'),/^https:\/\/open\.spotify\.com\/embed\//);
 // Revisiter la page dans la même session : le choix reste mémorisé (pas de re-consentement).
 await page.reload();
 await page.locator('#pg-presskit.active').waitFor();
 assert.equal(await page.locator('#pk-music [data-platform="soundcloud"] iframe').count(),1);
 assert.equal(await page.locator('#pk-music [data-platform="youtube"] iframe').count(),1);
 // resetEmbedConsent() (bouton Paramètres → Confidentialité) efface ce choix
 // et réaffiche immédiatement les placeholders sur la page ouverte.
 await page.evaluate(()=>resetEmbedConsent());
 assert.equal(await page.locator('#pk-music iframe').count(),0);
 assert.equal(await page.locator('#pk-music .pk-profile-player-gate').count(),4);
 assert.equal(await page.evaluate(()=>document.querySelector('#pk-booking').getBoundingClientRect().top>document.querySelector('#pk-profile-details').getBoundingClientRect().top),true);
 assert.match(await page.locator('#pk-hero-art').evaluate(el=>el.style.backgroundImage),/auth-hero-bg\.jpg/);
 assert.match(await page.locator('#pk-photo').getAttribute('src'),/avatar-03-pullup\.png/);
 assert.equal(await page.locator('#pk-genre-chips span').count(),6);
 assert.equal(await page.locator('#pk-genre-chips span').evaluateAll(chips=>new Set(chips.map(chip=>chip.offsetTop)).size),1);
 assert.equal(await page.evaluate(()=>{const hero=document.querySelector('.pk2-hero').getBoundingClientRect(),photo=document.querySelector('.pk3-avatar-stage').getBoundingClientRect();return Math.abs(hero.width-photo.width)<=2&&Math.abs(hero.height-photo.height)<=2;}),true);
 assert.equal(await page.evaluate(()=>djProfileUrl()),'http://127.0.0.1:3107/app?dj=public-test');
 assert.equal(await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 await page.waitForTimeout(500);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-mobile.png'),fullPage:true});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=620);
 await page.waitForTimeout(200);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-mobile-content.png'),fullPage:true});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=el.scrollHeight);
 await page.waitForTimeout(200);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-mobile-bottom.png'),fullPage:true});
 await page.setViewportSize({width:1280,height:900});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=0);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-desktop-top.png'),fullPage:true});
 await page.locator('#pg-presskit .scroll').evaluate(el=>el.scrollTop=760);
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'dj-public-profile-desktop.png'),fullPage:true});
 const relevant=errors.filter(e=>!e.includes('supabase')&&!e.includes('QRCode'));
 console.log('Browser errors:',errors);
 assert.deepEqual(relevant,[]);
 console.log('PASS: mobile/desktop, validation, six styles, search, 20 covers, form round-trip, press kit header; screenshots in /private/tmp.');
 }finally{await browser?.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
